version: "3.4"

services:

  app:
    build: .
    ports:
      - 5000:5000
    volumes:
      - ./:/var

  test:
    build:
      context: .
      dockerfile: test.Dockerfile
    volumes_from:
      - app